name: MrDoc_Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=aliyun6164502686 registry.cn-hangzhou.aliyuncs.com
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/oyyz_online/mr_doc:1.0.0
          # 推送镜像到镜像仓库
          docker push registry.cn-hangzhou.aliyuncs.com/oyyz_online/mr_doc:1.0.0
